[package]
name = "html-transformer"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.0"
lol_html = "2.2.0"
kuchikiki = "0.8.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.5.4"

[lib]
crate-type = ["cdylib"]
